Init computenest project.       on-behalf-of: @org aliyun-computenest@alibaba-inc.com

diff --git a/.computenest/ros_templates/template.yaml b/.computenest/ros_templates/template.yaml
--- a/.computenest/ros_templates/template.yaml
+++ b/.computenest/ros_templates/template.yaml
@@ -1,7 +1,7 @@
 ROSTemplateFormatVersion: '2015-09-01'
 Description:
-  en: Spring boot Demo
-  zh-cn:  Spring boot Demo
+  en: Source Code Service Ros Template
+  zh-cn: 源代码服务模板
 Parameters:
   PayType:
     Type: String
@@ -64,9 +64,10 @@ Parameters:
     AssociationProperty: ALIYUN::ECS::Instance::InstanceType
     AssociationPropertyMetadata:
       InstanceChargeType: ${PayType}
-    AllowedValues:
-      - ecs.c6.large
-      - ecs.c6.2xlarge
+      Constraints:
+        InstanceTypeFamily:
+          - ecs.u1
+          - ecs.e
   InstancePassword:
     NoEcho: true
     Type: String
@@ -89,33 +90,41 @@ Parameters:
       en: Zone ID
       zh-cn: 可用区ID
     AssociationProperty: ALIYUN::ECS::Instance::ZoneId
+  VpcId:
+    Type: String
+    Label:
+      en: VPC ID
+      zh-cn: 专有网络VPC实例ID
+    AssociationProperty: 'ALIYUN::ECS::VPC::VPCId'
+  VSwitchId:
+    Type: String
+    Label:
+      en: VSwitch ID
+      zh-cn: 交换机实例ID
+    Default: ''
+    AssociationProperty: 'ALIYUN::ECS::VSwitch::VSwitchId'
+    AssociationPropertyMetadata:
+      VpcId: VpcId
+      ZoneId: ZoneId
+  AdminPassword:
+    Type: String
+    AssociationProperty: ALIYUN::ECS::Instance::Password
+    Label: 管理员密码
+    NoEcho: True
 Resources:
-  Vpc:
-    Type: ALIYUN::ECS::VPC
-    Properties:
-      CidrBlock: 192.168.0.0/16
   SecurityGroup:
     Type: ALIYUN::ECS::SecurityGroup
     Properties:
       SecurityGroupName:
         Ref: ALIYUN::StackName
       VpcId:
-        Ref: Vpc
-      # 安全组入端口
+        Ref: VpcId
       SecurityGroupIngress:
-        - PortRange: 8080/8080
+        - PortRange: 80/80
           Priority: 1
           SourceCidrIp: 0.0.0.0/0
           IpProtocol: tcp
           NicType: internet
-  VSwitch:
-    Type: ALIYUN::ECS::VSwitch
-    Properties:
-      ZoneId:
-        Ref: ZoneId
-      VpcId:
-        Ref: Vpc
-      CidrBlock: 192.168.0.0/24
   InstanceGroup:
     Type: ALIYUN::ECS::InstanceGroup
     Properties:
@@ -127,24 +136,24 @@ Resources:
       Period:
         Ref: PayPeriod
       VpcId:
-        Ref: Vpc
+        Ref: VpcId
       VSwitchId:
-        Ref: VSwitch
-      SecurityGroupId:
-        Ref: SecurityGroup
+        Ref: VSwitchId
       ZoneId:
         Ref: ZoneId
-      ImageId: centos_7_8_x64_20G_alibase_20211130.vhd
+      SecurityGroupId:
+        Ref: SecurityGroup
+      ImageId: centos_7_9_x64_20G_alibase_20230613.vhd
       Password:
         Ref: InstancePassword
       InstanceType:
         Ref: EcsInstanceType
       SystemDiskCategory: cloud_essd
       SystemDiskSize: 200
-      InternetMaxBandwidthOut: 1
+      InternetMaxBandwidthOut: 5
       IoOptimized: optimized
       MaxAmount: 1
-  InstallPackage:
+  RunInstallCommand:
     Type: ALIYUN::ECS::RunCommand
     Properties:
       InstanceIds:
@@ -158,28 +167,99 @@ Resources:
         Fn::Sub:
           - |
             #!/bin/bash
-            yum install -y java
-            mkdir -p /home/admin/application
-            cd /home/admin/application
-            wget '{{ computenest::file::springboot }}' -O package.tgz
-            tar xvf package.tgz
-            /bin/bash deploy.sh start
-          - AccountId:
-              Ref: ALIYUN::TenantId
+            # 源代码通过computenest-cli被打包为tar.gz包，并发布为部署物
+            wget '{{ computenest::file::LYH-RAIN_springboot-ecs-package-demo }}' -O LYH-RAIN_springboot-ecs-package-demo.tar.gz > /var/log/download.log
+            tar -zxvf LYH-RAIN_springboot-ecs-package-demo.tar.gz && cd "$(tar -tzf LYH-RAIN_springboot-ecs-package-demo.tar.gz | head -1 | awk -F'/' '{print $1}')"
+            #!/bin/bash
+            # Check the operating system
+              # CentOS / Red Hat
+            sudo yum install -y java-1.8.0-openjdk
+            echo y | sudo yum install java-1.8.0-openjdk-devel
+            
+            echo 'export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk' >> ~/.bashrc
+            
+            echo 'export PATH=$JAVA_HOME/bin:$PATH' >> ~/.bashrc
+            source ~/.bashrc
+            
+            # Verify Java installation
+            java -version
+            
+              # 安装 Maven
+              if [[ "$OSTYPE" == "linux-gnu"* ]]; then
+                # Linux
+                sudo apt-get install -y maven
+              elif [[ "$OSTYPE" == "darwin"* ]]; then
+                # Mac
+                brew install maven
+              else
+                echo "Unsupported OS for Maven install: $OSTYPE"
+                exit 1
+              fi
+            
+            
+            sudo chmod -R 777 .
+            
+            tar -zxvf LYH-RAIN_SourceCodeCreation.tar.gz
+            cd demo1
+            mvn clean package
+            
+            # 指定目标目录为当前目录
+            target_directory="."
+            
+            # 在目标目录中查找名字以"server"结尾的.jar文件
+            find "${target_directory}" -type f -name "demo1*.jar" -print0 | while IFS= read -r -d '' file; do
+                # 输出包含目标文件的目录
+                directory=$(dirname "${file}")
+                echo "目录: ${directory}"
+            done
+            # 获取当前目录
+            current_directory=$(pwd)
+            
+            # 打印当前目录
+            echo "当前目录: ${current_directory}"
+            JAR_FILE="/home/admin/application/demo1/target/demo1-0.0.1-SNAPSHOT.jar"
+            
+            # 检查是否有同名的 Java 进程在运行
+            PID=$(jps -mlv | grep "$JAR_FILE" | awk '{print $1}')
+            
+            if [ -n "$PID" ]; then
+              echo "Found running process with PID: $PID"
+            
+              # 发送关闭信号给程序
+              kill -9 $PID
+            
+              # 等待一段时间，确保程序关闭
+              sleep 5
+            
+              # 再次检查是否还有进程在运行
+              PID=$(jps -mlv | grep "$JAR_FILE" | awk '{print $1}')
+            
+              if [ -n "$PID" ]; then
+                echo "Failed to gracefully stop the process with PID: $PID"
+                exit 1
+              else
+                echo "Successfully stopped the process"
+              fi
+            fi
+            sudo nohup java -jar /home/admin/application/boost.server/target/demo1-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &
+
+            ARGUS_VERSION=3.5.7 /bin/bash -c "$(curl -sS https://cms-agent-${RegionId}.oss-${RegionId}-internal.aliyuncs.com/Argus/agent_install_ecs-1.7.sh)" >> /root/install_cms_agent.log 2>&1
+          - RegionId:
+              Ref: ALIYUN::Region
 Outputs:
-  VisitUrl:
+  ServerAddress:
     Description:
-      en: VisitUrl.
+      en: ServerAddress.
       zh-cn: 访问页面。
     Value:
       Fn::Sub:
-      - http://${Address}:8080
-      - Address:
-          Fn::Select:
-          - 0
-          - Fn::GetAtt:
-            - InstanceGroup
-            - PublicIps
+        - 'http://${ServerAddress}:80'
+        - ServerAddress:
+            Fn::Select:
+            - 0
+            - Fn::GetAtt:
+              - InstanceGroup
+              - PublicIps
 Metadata:
   ALIYUN::ROS::Interface:
     ParameterGroups:
@@ -196,6 +276,13 @@ Metadata:
           default: 资源配置
       - Parameters:
           - ZoneId
+          - VpcId
+          - VSwitchId
         Label:
           default: 可用区配置
-
+      - Parameters:
+          - AdminPassword
+        Label:
+          en: Software Configuration
+          zh-cn: 软件配置
+      
